# Generated by Django 4.2.5 on 2023-09-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_caterogy_options_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caterogy',
            new_name='Category',
        ),
    ]
